services:
  edge-agent:
    build:
      context: .

    container_name: edge-agent

    restart: unless-stopped

    network_mode: host

    cap_add:
      - NET_ADMIN
      - NET_RAW

    volumes:
      - ./config.yaml:/etc/edge-agent/config.yaml:ro