package client

// ---------- Agent registration ----------

type RegisterRequest struct {
	AgentID string `json:"agent_id"`

	Capacity Capacity `json:"capacity"`
}

type Capacity struct {
	SNI   int `json:"sni"`
	Route int `json:"route"`
}

// ---------- Poll ----------

type PollRequest struct {
	AgentID string `json:"agent_id"`

	Max int `json:"max"`
}

type PollResponse struct {
	Revision uint64 `json:"revision"`

	Leases []Lease `json:"leases"`
}

// ---------- Lease ----------

type Lease struct {
	ID string `json:"id"`

	Domain string `json:"domain"`

	Type string `json:"type"`

	State string `json:"state"`

	AgentID string `json:"agent_id,omitempty"`

	ExpiresAt string `json:"expires_at,omitempty"`

	// Edge/public address allocated by the edge-agent.
	Address string `json:"address,omitempty"`

	// Route identifier generated by the control plane/agent.
	RouteID string `json:"route_id,omitempty"`

	// Destination for packet forwarding.
	DestinationIP string `json:"destination_ip,omitempty"`

	// tcp or udp.
	Protocol string `json:"protocol,omitempty"`

	// Destination port.
	DestinationPort uint16 `json:"destination_port,omitempty"`

	// Optional source port restriction.
	SourcePort uint16 `json:"source_port,omitempty"`
}

// ---------- Heartbeat ----------

type HeartbeatRequest struct {
	AgentID string `json:"agent_id"`

	LeaseIDs []string `json:"lease_ids"`
}

// ---------- Report ----------

type ReportRequest struct {
	AgentID string `json:"agent_id"`

	LeaseID string `json:"lease_id"`

	Success bool `json:"success"`

	Address string `json:"address,omitempty"`

	SNI string `json:"sni,omitempty"`

	RouteID string `json:"route_id,omitempty"`

	DestinationIP string `json:"destination_ip,omitempty"`

	Protocol string `json:"protocol,omitempty"`

	DestinationPort uint16 `json:"destination_port,omitempty"`

	SourcePort uint16 `json:"source_port,omitempty"`
}
